app/blog/__init__.py
from flask import Blueprint

# this blueprint handles main blog functions: list posts, view post, edit post (for admin only),
# delete post (for admin only), etc
bp = Blueprint('blog', __name__)

from app.blog import routes

app/blog/routes.py
import re
import uuid
import os

from flask import (render_template, make_response, request, redirect, url_for, abort)
from app.blog import bp
from app import notifications
from app.utils import (check_hashed_password, timestamp_to_str, str_to_timestamp, timestamp_to_dt, markup, user_has_permission, article_url, normalize_email)
from app.utils.PyRSS2Gen import RSS2, RSSItem
from app.models import (User, Article, Comment, Tag, VerifiedEmail, File)
from app.models.config import get as get_config
from app.models.article import get_public_tags_cloud
from app.extensions import db
from sqlalchemy import func
from app.files import FILES_PATH

from flask_babel import gettext as _
from flask_login import (login_user, logout_user, login_required, current_user)
from time import time

@bp.route('/')
def index():
    """
    Display list of articles sorted by publishing date ascending,
    show rendered previews, not complete articles
    """
    ctx = {
        'articles': [],
        'prev_page': None,
        'next_page': None
    }
    page_size = int(get_config('elements_on_page'))
    start_page = 0
    if 'start' in request.args:
        try:
            start_page = int(request.args['start'])
            if start_page < 0:
                start_page = 0
        except ValueError:
            start_page = 0
    
    dbsession = db.session
    user = current_user

    q = dbsession.query(Article).options(db.joinedload(Article.tags)).options(db.joinedload(Article.user)).order_by(Article.published.desc())
    # print(current_user)
    if user.is_anonymous:
        q = q.filter(Article.is_draft==False)

    ctx['articles'] = q[(start_page * page_size):(start_page+1) * page_size + 1]

    #for article in ctx['articles']:
    #    log.debug(article.shortcut_date)

    if len(ctx['articles']) > page_size:
        ctx['prev_page'] = url_for('blog.index', start=start_page+1)
        ctx['articles'].pop()

    ctx['next_page'] = None
    if start_page > 0:
        ctx['next_page'] = url_for('blog.indx', start=start_page+1)

    ctx['page_title'] = _('Latest articles')

    return render_template('blog/index.jinja2', **ctx)


@bp.route('/files/f/<filename>')
def download_file(filename):
    dbsession = db.session

    dbfile = dbsession.query(File).filter(File.name==filename).first()
    if dbfile is None:
        abort(404)

    full_filename = os.path.join(FILES_PATH, filename)
    data = open(full_filename, 'rb').read()
    resp = make_response(data)
    resp.mimetype = dbfile.content_type
    return resp


@bp.route('/rss/latest')
def latest_rss():
    dbsession = db.session

    q = dbsession.query(Article).options(db.joinedload(Article.tags))\
        .options(db.joinedload(Article.user))\
        .filter(Article.is_draft==False).order_by(Article.updated.desc())
    articles = q[0:10]
    rss_title = get_config('site_title') + ' - ' + _('Latest articles feed')
    site_base_url = get_config('site_base_url')
    items = []

    '''
    feed = Rss201rev2Feed(
        title=rss_title,
        link=site_base_url,
        description='',
        language='en')
    '''

    for a in articles:
        link = article_url(a)
        tags_list = []
        for t in a.tags:
            tags_list.append(t.tag)
        items.append(RSSItem(title=a.title, link=link, description=a.rendered_preview, pubDate=timestamp_to_dt(a.published),
            guid=str(a.id)))

    feed = RSS2(
        title=rss_title,
        link=site_base_url,
        description='',
        items=items,
        generator='pyrengine'
        )

    # response = Response(body=feed.to_xml(encoding='utf-8'), content_type='application/rss+xml')
    resp = make_response(feed.to_xml(encoding='utf-8'), )
    return resp


@bp.route('/tag/<tag>')
def articles_by_tag(tag):
    return ''


@bp.route('/help/article-markup')
def article_markup_help():
    return render_template('blog/markup_help.jinja2')


@bp.route('/<path:shortcut_date>/<shortcut>')
def view_article(shortcut_date, shortcut):
    dbsession = db.session
    q = dbsession.query(Article).filter(Article.shortcut_date == shortcut_date)\
        .filter(Article.shortcut == shortcut)
    article = q.first()

    if article is None:
        abort(404)

    return _view_article(article)

def _view_article(article):
    user = current_user
    if not user_has_permission(user, 'editor') and article.is_draft:
        abort(404)

    dbsession = db.session
    comments = dbsession.query(Comment).filter(Comment.article == article).all()
    comments_dict = {}

    for x in comments:
        if x.parent_id not in comments_dict:
            comments_dict[x.parent_id] = []
        if x.user is not None:
            x._real_email = x.user.email
        else:
            x._real_email = x.email
        if x._real_email == '':
            x._real_email = None
        comments_dict[x.parent_id].append(x)

    scope = {'thread': []}

    # we should hide all not approved comments for everyone who isn't a site admin
    display_not_approved = user_has_permission(user, 'admin')

    def build_thread(parent_id, indent):
        if parent_id not in comments_dict:
            return

        for x in comments_dict[parent_id]:
            if not display_not_approved and not x.is_approved:
                continue
            setattr(x, '_indent', indent)
            scope['thread'].append(x)
            build_thread(x.id, indent+1)

    build_thread(None, 0)
    ctx = {
        'article': article
    }
    ctx['comments'] = scope['thread']
    # ctx['comments_html'] = 'COMMENTS'

    signature = str(uuid.uuid4()).replace('-', '')
    is_subscribed = False

    for cn in ('comment_display_name', 'comment_email', 'comment_website'):
        if cn in request.cookies:
            ctx[cn] = request.cookies[cn]
        else:
            ctx[cn] = ''

    if 'is_subscribed' in request.cookies and request.cookies['is_subscribed'] == 'true':
        is_subscribed = True

    ctx['article'] = article
    ctx['signature'] = signature
    ctx['is_subscribed'] = is_subscribed

    return render_template('blog/view_article.jinja2', **ctx)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('account/login.jinja2')
    else:
        form = request.form
        login = request.form.get('login')
        password = request.form.get('password')
        dbsession = db.session
        u = dbsession.query(User).filter(User.login == login).first()

        if u is not None:
            if not check_hashed_password(password, u.password):
                u = None
            else:
                # authenticate
                login_user(u, remember=True)
        
        if u is None:
            ctx = {
                'error': _('User not found'),
                'login': login
            }
            return render_template('account/login.jinja2', **ctx)
        else:
            return redirect(url_for('blog.index'))


@bp.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    return {'success': True}


@bp.route('/write', methods=['GET', 'POST'])
@login_required
def write_article():
    ctx = {
        'submit_url': url_for('blog.write_article'),
        'mode': 'create',
        # 'save_url_ajax': url_for('blog.write_article_ajax'),
        'errors': {}
    }
    if request.method == 'GET':
        ctx['form'] = {
            'title': _('New article title'),
            'shortcut': 'new-article-shortcut',
            'published': timestamp_to_str(time()),  # current time
            'tags': '',
            'body': '',
            'is_draft': True,
            'is_commentable': True
        }
        return render_template('blog/edit_article.jinja2', **ctx)
    else:
        ctx['form'] = {x:request.form.get(x) for x in ('title', 'shortcut', 'published', 'tags', 'body') }
        ctx['form']['is_draft'] = request.form.get('is_draft') is not None
        ctx['form']['is_commentable'] = request.form.get('is_commentable') is not None

        errors = _verify_article_form(ctx['form'])

        article = Article()
        article.user = current_user
        for field_name in ('title', 'shortcut', 'is_draft', 'is_commentable'):
            setattr(article, field_name, ctx['form'][field_name])
        article.published = str_to_timestamp(ctx['form']['published'])
        date_re = re.compile('^([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2})$')
        mo = date_re.match(ctx['form']['published'])
        v = [int(x) for x in mo.groups()[0:3]]
        article.shortcut_date = '{0:04d}/{1:02d}/{2:02d}'.format(*v)
        article.set_body(ctx['form']['body'])
        
        dbsession = db.session
        q = dbsession.query(Article).filter(Article.shortcut_date == article.shortcut_date)\
            .filter(Article.shortcut == article.shortcut)
        res = q.first()
        if res is not None:
            errors.append(('shortcut', _('Article with the same shortcut already exists.')))

        tags_str = ctx['form']['tags']
        tags = set([s.strip() for s in tags_str.split(',') if s != ''])

        for field_name, e in errors:
            if field_name not in ctx['errors']:
                ctx['errors'][field_name] = ''
            ctx['errors'][field_name] += e + ' '

        if len(errors) == 0:
            # create database object
            dbsession.add(article)
            dbsession.flush()  # required as we need to obtain article_id
            for tag_str in tags:
                tag = Tag(tag_str, article)
                dbsession.add(tag)
            dbsession.commit()

            get_public_tags_cloud(force_reload=True)

            return redirect(article_url(article))
        else:
            return render_template('blog/edit_article.jinja2', **ctx)


def _update_article(article, ctx):
    ctx['form'] = {x:request.form.get(x) for x in ('title', 'shortcut', 'published', 'tags', 'body') }

app/templates/blog/edit_article.html
{% extends 'base.html' %}

{% block title %}{% if mode == 'create' %}{{ _('Write a new article') }}{% else %}{{ _('Edit article') }}{% endif %}{% endblock %}

{% block content %}
<form action="{{ submit_url }}" method="POST" id="form" onsubmit="return pyrengine.articleCheckForm();">
  <dl class="form">
    <dt>{{ _('Subject (required)') }}</dt>
    <div id="error-title" class="error" style="{% if not errors['title'] %}display: none;{% endif %}">{{ errors['title'] }}</div>
    <dd><input type="text" name="title" id="fid-title" value="{{ form['title'] }}"></dd>

    <dt><acronym title="{{ _('Short string (part of the URL), alphanumeric characters and “-” are recommended.') }}">{{ _('Shortcut (required)') }}</acronym></dt>
    <div id="error-shortcut" class="error" style="{% if not errors['shortcut'] %}display: none;{% endif %}">{{ errors['shortcut'] }}</div>
    <dd><input type="text" name="shortcut" id="fid-shortcut" value="{{ form['shortcut'] }}"></dd>

    <dt><acronym title="{{ _('Format: YYYY-MM-DD HH:MM') }}">{{ _('Publishing date and time') }}</acronym></dt>
    <div id="error-published" class="error" style="{% if not errors['published'] %}display: none;{% endif %}">{{ errors['published'] }}</div>
    <dd><input type="text" name="published" id="fid-published" value="{{ form['published'] }}"></dd>

    <dt>{{ _('Tags (comma separated)') }}</dt>
    <div id="error-tags" class="error" style="display: none;"></div>
    <dd><input type="text" name="tags" id="fid-tags" value="{{ form['tags'] }}"></dd>

    <div>{{ _('Article body (required, markup: *<em>italic</em>*, **<strong>bold</strong>**, [hyperlink](http://example.com) <a href="{0}" target="_blank" class="new-window">more</a>)').format(url_for('blog.markup_help')) }}</div>

    <!-- body text control buttons -->
    <div class="editor-text-controls">
      <span class="button" onclick="pyrengine.editorWrap('fid-body', '`');" title="{{ _('Inline code (monospace text)') }}">`$x`</span>
      <span class="button" onclick="pyrengine.editorWrap('fid-body', '*');" title="{{ _('Emphasis (italic)') }}"><em>I</em>&nbsp;</span>
      <span class="button" onclick="pyrengine.editorWrap('fid-body', '**');" title="{{ _('Strong text (bold)') }}"><strong>B</strong></span>
      <span class="button" onclick="pyrengine.editorBlockquote('fid-body');" title="{{ _('Quotation') }}">&gt;</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '❈ ❈ ❈ {@class=center}\n');" title="{{ _('Insert dinkus') }}">❈ ❈ ❈</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '────────────────── {@class=center}\n');" title="{{ _('Insert dinkus') }}">──</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '══════════════════ {@class=center}\n');" title="{{ _('Insert dinkus') }}">══</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '~~~~~shell-session\n[user@shell]% \n~~~~~\n');" title="{{ _('Insert shell code') }}">sh $</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '{@style=color:red;}');" title="{{ _('Insert paragraph color text') }}"><span style="color: red;">red</span></span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '[TEXT](https://)');" title="{{ _('Insert hyperlink template') }}">&lt;a&gt;</span>
    </div>

    <div id="error-body" class="error" style="{% if not errors['body'] %}display: none;{% endif %}">{{ errors['body'] }}</div>
    <dd><textarea type="text" name="body" id="fid-body">{{ form['body'] }}</textarea></dd>

    <dd><label><input type="checkbox" name="is_draft" id="fid-is_draft"{% if form['is_draft'] %} checked="checked"{% endif %}> <acronym title="{{ _('if checked article will be visible to blog administrator only') }}">{{ _('draft article') }}</acronym></label></dd>
    <dd><label><input type="checkbox" name="is_commentable" id="fid-is_commentable"{% if form['is_commentable'] %} checked="checked"{% endif %}> {{ _('allow visitors comments') }}</label></dd>
    
    <dd>{% if mode == 'edit' %}<button class="button" onclick="pyrengine.saveArticle('{{ save_url_ajax }}'); return false;">{{ _('save and continue editing') }}</button> {% endif %}<button class="button" onclick="$('#form').submit(); return false;"><span class="fa fa-save"></span> {{ _('save') }}</button>

    <button class="button" onclick="pyrengine.previewArticle(); return false;"><span class="fa fa-flask"></span> {{ _('preview') }}</button></dd>
  </dl>
</form>

<div id="eid-article-notify" class="notify" style="display:none;"></div>
<div id="eid-article-warning" class="warning" style="display:none;"></div>
<div id="eid-article-render-preview" style="display: none;"></div>

{% endblock %}

app/templates/blog/index.html
{% extends 'base.html' %}

{% set editor_permission = h.user_has_permission(current_user, 'editor') %}
{% set admin_permission = h.user_has_permission(current_user, 'admin') %}

{% block title %}{{ _('Recent articles') }}{% endblock %}

{% block content %}
{% for article in articles %}
<div class="article-preview">
  <div class="title">
    {% if editor_permission %}
      <div class="article-actions">
        <a href="{{ url_for('blog.edit_article', article_id=article.id) }}" class="border-icon" title="{{ _('edit') }}"><span class="fa fa-pencil"></span></a>
        <a href="#" onclick="pyrengine.deleteArticle('{{ url_for('blog.delete_article_ajax', article_id=article.id) }}', '{{ article.id }}'); return false;" class="border-icon" title="{{ _('delete') }}"><span class="fa fa-trash-o"></span></a>
      </div>
    {% endif %}
    <a href="{{ h.article_url(article) }}">{{ article.title }}</a>{% if article.is_draft %} <span class="warning">{{_('draft') }}</span>{% endif %}</a>
  </div>
  <div class="date">{{ '{author} | {date}'.format(author=article.user.display_name, date=h.timestamp_to_str(article.published, _('DATE_TIME_SHORT'))) }}</div>
  <div class="before-preview"></div>
  <div class="preview">{{ article.get_html_preview() | safe }}</div>
  {% if article.is_splitted %}<div class="splitter"><a href="{{ h.article_url(article) }}">{{ _('continue reading') }}</a></div>{% endif %}
  <div class="tags">{{ _('Tags:') }} {% for tag in article.tags %}<a href="{{ url_for('blog.articles_by_tag', tag=tag.tag) }}">#{{ tag.tag }}</a> {% endfor %}</div>
  <div class="footer">
    {% if article.comments_approved > 0 %}
      <a href="{{ h.article_url(article) }}#comments">{{ _('Comments:') }} {{ article.comments_approved }}</a>
    {% else %}
      {{ _('Comments:') }} 0
    {% endif %}
  </div>
</div>
<div class="article-preview-after"></div>
{% endfor %}

{% if articles|length == 0 %}
  {{ _('No articles here.') }}
{% endif %}

<div class="pager">
{% if next_page is none %} {{ _('<-newer') }} {% else %} <a href="{{ next_page }}">_('<-newer')</a> {% endif %}
{% if prev_page is none %} {{ _('older->') }} {% else %} <a href="{{ prev_page }}">_('older->')</a> {% endif %}
</div>

{% endblock %}

app/templates/blog/markup-help.html
{% extends 'base.html' %}

{% block title %}Markup language for pyrengine{% endblock %}

{% block content %}
<h2>Pyrengine text markup language for articles</h2>

<div>Pyrengine uses Markdown-based markup language, it supports complete core 
    Markdown elements set plus some additional features.</div>

<div>Please consult official Markdown 
    <a href="http://daringfireball.net/projects/markdown/syntax">syntax documentation</a> 
    for complete language reference and Python Markdown <a href="https://python-markdown.github.io/">documentation site</a>. In paragraphs below we are describing 
    most used language construction.</div>

<h2>Basic markup</h2>

<div class="article">

<div>Use an empty line to split text into separate paragraphs, each paragraph consists of non-empty text lines.</div>

<pre><code>Just write text, insert line breaks
to format it appropriately.
This is still the same paragraph.

And this is a new one.

And another. Remember: the empty line creates paragraphs.</code></pre>

<div>You can also create headers, to do so just prepend a line with some
#-characters, one # stands for the top-level header with largest text,
## stands for second-level header etc up to six #-s. There is an also alternative
way to create headers, just underscore the line with some “=” or “-” charecters
to create 1st and 2nd level headers correspondingly.</div>

<pre><code># This is the largest-font header

And this is the 1st level header too
====================================

And 2nd level
-------------

###### This is the smallest possible header</code></pre>

<div>Inline text formatting is easy: enclose text in *-s to create 
*<em>emphasized</em>* text and in double *-s **<strong>strong</strong>**
text. Emphasized text is displayed as italic, and strong as an embolden text. 
And of course there is an alternative: enclose phrase in underscores to create
emphasized, and use triple *-s to create ***<strong><em>strong emphasis</em></strong>***.
</div>

<pre><code>The next word is *emphasized* this _emphasized_ too, and this **a strong text**.
Strong ***emphasis***.</code></pre>

<div>Lists are also easy, put each list item on separate line and prepend it with *, to create sublists place an indent before the *. </div>

<div>In order to insert monospaced font (for inline code samples for example) use backticks (`), like this `<code>$x = sort($list);</code>`. If the code contains backtick then 
enclose it with two backticks and so on: ``<code>$x = `ls`;</code>``.</div>

<pre><code>* first list item
* second, and the next items are indented
    * these are
    * sublist items
* and continue the main list</code></pre>

<div>You can split long lines into, just remember: empty line creates paragraph break, indent line with the same amount of
spaces as line above.</div>

<pre><code>* first list item
* second list item
  continues here
  it's still single paragraph inside
  one list item
</code></pre>

<div>Ordered lists are also simple:</div>

<pre><code>1. First list item;
1. Second
    * nested
    * unordered
    * list</code></pre>

<div>Hypelinks are bit tricky,   intentionally doesn't parse URL-like 
character sequences and doesn't automatically transform them into the links.
So you need to explicitly mark URLs: this text, for example, 
&lt;https://github.com/sigsergv/pyrengine&gt; will be converted to clickable 
hyperlink 
<a href="https://github.com/sigsergv/pyrengine">https://github.com/sigsergv/pyrengine</a>. 
Email addresses also processed in similar way: &lt;sergei@regolit.com&gt; will be
converted to mailto-hyperlink <a href="mailto:sergei@regolit.com">sergei@regolit.com</a>.
</div>

<pre><code>Visit google website &lt;http://google.com> to search 
internet about markdown.</code></pre>

<div>You can use customized hyperlinks, see below an example, it will be displayed as
<a href="http://google.com">Google</a>:</div>

<pre><code>[Google](http://google.com)</code></pre>

<div>It's possible to insert inline images, to do so use the following code,
it will show the image <img alt="alt text" src="/static/images/sample-image.png"/>:</div>

<pre><code>![alt text](http://example.com/static/images/sample-image.png)</code></pre>

<div>Quotation, just put character <code>></code> at the beginning of first line of block
that needs to be rendered as quoatation.</div>

<pre><code>> This is a quitation.
It could be multiline.
>
> And even multi-paragraph!</code></pre>

</div>


<h2>Extended markup</h2>

<div class="article">

<div>Extended markup is not a part of original markdown specs so the code 
below has to be used in pyrengine only.</div>

<h3>Images from pyrengine storage</h3>

<div>Pyrengine has its own file storage and you can use pictures stored there in 
your articles, syntax code for that is very similar to one that is
used for inserting external images:</div>

<pre><code>This is a picture named `file-name.jpg` from internal storage:

!![alt text](file-name.jpg)</code></pre>

<div>If that image in the storage is too large you can display instead reduced-size
picture, it's also a hyperlink that opens an original picture (we added <code>/m</code>
suffix to picture name):</div>

<pre><code>!![alt text](file-name.jpg/m)</code></pre>

<h3>HTML elements attributes</h3>

<div>It's possible to set custom html elements attributes, it's required sometimes
to finely tune generated HTML code, for example, you can insert inline images (that are
float in the text) using this code:</div>

<pre><code>![ALT-TEXT{@style=float:left;}](http://example.com/image/url.png)</code></pre>

<div>it will add additional attribute <code>style="float:left;"</code> to generated
HTML element IMG.</div>


<h3>Footnotes</h3>

<div>You can insert footnotes with hyperlinks, so if you want to create
footnote, place footnote marker <code>[^fn-1]</code> in the text 
(you can use any characters instead of <code>fn-1</code>, numbers, for example) and 
place footnote content somewhere in the article (at the very end of it
for example):</div>

<pre><code>Footnotes look nice[^fn-1], but unfortunately they break
attention focus[^fn-2].

[^fn-1]: So cute tiny hyperlinks!
[^fn-2]: You need to read text somewhere else and then return to main
text flow. So this footnotes block will be rendered after the article, and
numbered hyperlinks are placed in the main text.</code></pre>


<h3>Definition lists</h3>

<div>Inspired by HTML elements &lt;DL>, &lt;DD> and &lt;DT>:</div>

<pre><code>**First term**
:   defintion data

**Multiline**
:   Multiline defintion lines
    are possible, just prepend 
    lines with 4 spaces

Plain term (not strong)
:   And its definition
</code></pre>

<div>will be rendered into the following HTML:</div>

<pre><code>&lt;dl>
&lt;dt>&lt;strong>First term&lt;/strong>&lt;/dt>
&lt;dd>defintion data&lt;/dd>

&lt;dt>&lt;strong>&lt;/strong>&lt;/dt>
&lt;dd>Multiline defintion lines 
are possible, just prepend lines 
with 4 spaces&lt;/dd>

&lt;dt>Plain term (not strong)&lt;/dt>
&lt;dd>And its definition&lt;/dd>
&lt;/dl></code></pre>

<h3>Coloured code</h3>

<div>This construction will generate block coloured as C++ source code, <code>cpp</code> specifies source code language and won't be include in the
resulting html code.</div>

<pre><code>~~~~~cpp
for (int x=0; x&lt;666; ++x) {
    z();
}
~~~~~</code></pre>

<div>Here is the resulting output:</div>

<div class="codehilite"><pre><span class="k">for</span> <span class="p">(</span><span class="kt">int</span> <span class="n">x</span><span class="o">=</span><span class="mi">0</span><span class="p">;</span> <span class="n">x</span><span class="o">&lt;</span><span class="mi">666</span><span class="p">;</span> <span class="o">++</span><span class="n">x</span><span class="p">)</span> <span class="p">{</span>
    <span class="n">z</span><span class="p">();</span>
<span class="p">}</span>
</pre></div>

<div>If you don't specify source code language the code block will be displayed 
as regular code block without any source language guesses.</div>

<div>You can also render code with line numbers, to do that put the following construction
as the first line of code (instead of <code>cpp</code> you can use another language): <code>#!cpp</code>.</div>

<pre><code>~~~~~
#!cpp
// the line above will not be rendered
for (int x=0; x&lt;666; ++x) {
    z();
}
~~~~~</code></pre>

And you can insert listings from Linux terminal:

<pre><code>~~~~shell-session
[user@shell]% head -n 2 /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
~~~~
</code></pre>

It's rendered into this:

<div class="codehilite"><pre><span></span><span class="gp">[user@shell]%</span> head -n <span class="m">2</span> /etc/passwd
<span class="go">root:x:0:0:root:/root:/bin/bash</span>
<span class="go">daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin</span>
</pre></div>


<h3>Splitting long articles</h3>

<div>You can split large article into two parts using construction &lt;cut>. After rendering only the text 
before &lt;cut> (“preview”) will be displayed in the articles list and after that preview hyperlink pointing to complete article will be
place.
</div>

<pre><code>This is a short article description.

&lt;cut>

And this is a remaining part of the article.</code></pre>

<h3>Using TOC</h3>

<div>To insert TOC put this line to any document position:</div>

<pre><code>[TOC]
</code></pre>

Detailed extension description available on its web page: <a href="https://python-markdown.github.io/extensions/toc/">https://python-markdown.github.io/extensions/toc/</a>.

</div>

<h2>Usefull additions</h2>
<div class="article">

<div>You can use some decorations to improve text presentation. For example, to insert <em>dinkus</em> use one of these lines:

<pre><code>❈ ❈ ❈ {@class=center}

⁂ {@class=center}

❦ ❦ ❦ {@class=center}

❧ {@class=center}

○ ○ ○ {@class=center}
</code></pre>

You can change color of text in the paragraph, to do that use this code:

<pre><code>{@style=color:red;} This paragraph is rendered by red color.
</code></pre>

</div>
</div>
{% endblock %}