pyrengine/blog/__init__.py
from flask import Blueprint

# this blueprint handles main blog functions: list posts, view post, edit post (for admin only),
# delete post (for admin only), etc
bp = Blueprint('blog', __name__)

from pyrengine.blog import routes

pyrengine/blog/routes.py
import re
import uuid
import os

from flask import (render_template, make_response, request, redirect, url_for, abort, send_file)
from pyrengine.blog import bp
from pyrengine import notifications
from pyrengine.utils import (hash_password, check_hashed_password, timestamp_to_str, str_to_timestamp, timestamp_to_dt, markup, user_has_permission, article_url, normalize_email, package_file_path)
from pyrengine.utils.PyRSS2Gen import RSS2, RSSItem
from pyrengine.models import (User, Article, Comment, Tag, VerifiedEmail, File)
from pyrengine.models.config import get as get_config
from pyrengine.models.article import get_public_tags_cloud
from pyrengine.extensions import db
from sqlalchemy import func
from pyrengine.files import FILES_PATH, PREVIEWS_PATH
from PIL import Image

from flask_babel import gettext as _
from flask_login import (login_user, logout_user, login_required, current_user)
from time import time

@bp.route('/')
def index():
    """
    Display list of articles sorted by publishing date ascending,
    show rendered previews, not complete articles
    """
    ctx = {
        'articles': [],
        'prev_page': None,
        'next_page': None
    }
    page_size = int(get_config('elements_on_page'))
    start_page = 0
    if 'start' in request.args:
        try:
            start_page = int(request.args['start'])
            if start_page < 0:
                start_page = 0
        except ValueError:
            start_page = 0
    
    dbsession = db.session
    user = current_user

    q = dbsession.query(Article).options(db.joinedload(Article.tags)).options(db.joinedload(Article.user)).order_by(Article.published.desc())
    # print(current_user)
    if user.is_anonymous:
        q = q.filter(Article.is_draft==False)

    ctx['articles'] = q[(start_page * page_size):(start_page+1) * page_size + 1]

    #for article in ctx['articles']:
    #    log.debug(article.shortcut_date)

    if len(ctx['articles']) > page_size:
        ctx['prev_page'] = url_for('blog.index', start=start_page+1)
        ctx['articles'].pop()

    ctx['next_page'] = None
    if start_page > 0:
        ctx['next_page'] = url_for('blog.index', start=start_page-1)

    ctx['page_title'] = _('Latest articles')

    return render_template('blog/index.jinja2', **ctx)


@bp.route('/favicon.png')
def favicon_png():
    return send_file(package_file_path('examples/favicon.png'))


@bp.route('/files/f/<filename>')
def download_file(filename):
    dbsession = db.session

    dbfile = dbsession.query(File).filter(File.name==filename).first()
    if dbfile is None:
        abort(404)

    full_filename = os.path.join(FILES_PATH, filename)
    data = open(full_filename, 'rb').read()
    resp = make_response(data)
    resp.mimetype = dbfile.content_type
    return resp


@bp.route('/files/p/<filename>')
def download_file_preview(filename):
    dbsession = db.session

    dbfile = dbsession.query(File).filter(File.name==filename).first()
    if dbfile is None:
        abort(404)
    if dbfile.content_type not in ('image/jpeg', 'image/png', 'image/jpg'):
        abort(404)

    full_path = os.path.join(FILES_PATH, filename)
    preview_path = os.path.join(PREVIEWS_PATH, filename)
    # create preview file if required
    if not os.path.exists(preview_path):
        try:
            preview_max_width = int(get_config('image_preview_width', 300))
        except ValueError:
            preview_max_width = 300
        except TypeError:
            preview_max_width = 300
        im = Image.open(full_path)
        if im.size[0] <= preview_max_width:
            # don't need a resize
            preview_path = full_path
        else:
            h = (im.size[1] * preview_max_width) / im.size[0]
            resized = im.resize((preview_max_width, int(h)), Image.BILINEAR)
            resized.save(preview_path)

    data = open(preview_path, 'rb').read()
    resp = make_response(data)
    resp.mimetype = dbfile.content_type
    return resp


@bp.route('/rss/latest')
def latest_rss():
    dbsession = db.session

    q = dbsession.query(Article).options(db.joinedload(Article.tags))\
        .options(db.joinedload(Article.user))\
        .filter(Article.is_draft==False).order_by(Article.updated.desc())
    articles = q[0:10]
    rss_title = get_config('site_title') + ' - ' + _('Latest articles feed')
    site_base_url = get_config('site_base_url')
    items = []

    '''
    feed = Rss201rev2Feed(
        title=rss_title,
        link=site_base_url,
        description='',
        language='en')
    '''

    for a in articles:
        link = article_url(a)
        tags_list = []
        for t in a.tags:
            tags_list.append(t.tag)
        items.append(RSSItem(title=a.title, link=link, description=a.rendered_preview, pubDate=timestamp_to_dt(a.published),
            guid=str(a.id)))

    feed = RSS2(
        title=rss_title,
        link=site_base_url,
        description='',
        items=items,
        generator='pyrengine'
        )

    resp = make_response(feed.to_xml(encoding='utf-8'), )
    return resp


@bp.route('/tag/<tag>')
def articles_by_tag(tag):
    ctx = {
        'articles': [],
        'prev_page': None,
        'next_page': None
    }
    page_size = int(get_config('elements_on_page'))
    start_page = 0
    if 'start' in request.args:
        try:
            start_page = int(request.args['start'])
            if start_page < 0:
                start_page = 0
        except ValueError:
            start_page = 0

    dbsession = db.session
    user = current_user

    q = dbsession.query(Article).join(Tag).options(db.joinedload(Article.tags)).options(db.joinedload(Article.user)).order_by(Article.published.desc())
    # print(current_user)
    if user.is_anonymous:
        q = q.filter(Article.is_draft==False)

    q = q.filter(Tag.tag == tag)

    ctx['articles'] = q[(start_page * page_size):(start_page+1) * page_size + 1]

    #for article in ctx['articles']:
    #    log.debug(article.shortcut_date)

    if len(ctx['articles']) > page_size:
        ctx['prev_page'] = url_for('blog.articles_by_tag', tag=tag, start=start_page+1)
        ctx['articles'].pop()

    ctx['next_page'] = None
    if start_page > 0:
        ctx['next_page'] = url_for('blog.articles_by_tag', tag=tag, start=start_page-1)

    ctx['page_title'] = _('Articles with tag “{0}”').format(tag)

    return render_template('blog/index.jinja2', **ctx)


@bp.route('/help/article-markup')
def article_markup_help():
    return render_template('blog/markup_help.jinja2')


@bp.route('/<path:shortcut_date>/<shortcut>')
def view_article(shortcut_date, shortcut):
    dbsession = db.session
    q = dbsession.query(Article).filter(Article.shortcut_date == shortcut_date)\
        .filter(Article.shortcut == shortcut)
    article = q.first()

    if article is None:
        abort(404)

    return _view_article(article)

def _view_article(article):
    user = current_user
    if not user_has_permission(user, 'editor') and article.is_draft:
        abort(404)

    dbsession = db.session
    comments = dbsession.query(Comment).filter(Comment.article == article).all()
    comments_dict = {}

    for x in comments:
        if x.parent_id not in comments_dict:
            comments_dict[x.parent_id] = []
        if x.user is not None:
            x._real_email = x.user.email
        else:
            x._real_email = x.email
        if x._real_email == '':
            x._real_email = None
        comments_dict[x.parent_id].append(x)

    scope = {'thread': []}

    # we should hide all not approved comments for everyone who isn't a site admin
    display_not_approved = user_has_permission(user, 'admin')

    def build_thread(parent_id, indent):
        if parent_id not in comments_dict:
            return

        for x in comments_dict[parent_id]:
            if not display_not_approved and not x.is_approved:
                continue
            setattr(x, '_indent', indent)
            scope['thread'].append(x)
            build_thread(x.id, indent+1)

    build_thread(None, 0)
    ctx = {
        'article': article
    }
    ctx['comments'] = scope['thread']
    # ctx['comments_html'] = 'COMMENTS'

    signature = str(uuid.uuid4()).replace('-', '')
    is_subscribed = False

    for cn in ('comment_display_name', 'comment_email', 'comment_website'):
        if cn in request.cookies:
            ctx[cn] = request.cookies[cn]
        else:
            ctx[cn] = ''

    if 'is_subscribed' in request.cookies and request.cookies['is_subscribed'] == 'true':
        is_subscribed = True

    ctx['article'] = article
    ctx['signature'] = signature
    ctx['is_subscribed'] = is_subscribed

    return render_template('blog/view_article.jinja2', **ctx)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('account/login.jinja2')
    else:
        form = request.form
        login = request.form.get('login')
        password = request.form.get('password')
        dbsession = db.session
        u = dbsession.query(User).filter(User.login == login).first()

        if u is not None:
            if not check_hashed_password(password, u.password):
                u = None
            else:
                # authenticate
                login_user(u, remember=True)
        
        if u is None:
            ctx = {
                'error': _('User not found'),
                'login': login
            }
            return render_template('account/login.jinja2', **ctx)
        else:
            return redirect(url_for('blog.index'))


@bp.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    return {'success': True}


@bp.route('/write', methods=['GET', 'POST'])
@login_required
def write_article():
    ctx = {
        'submit_url': url_for('blog.write_article'),
        'mode': 'create',
        # 'save_url_ajax': url_for('blog.write_article_ajax'),
        'errors': {}
    }

pyrengine/templates/blog/article_comment.jinja2
{% include '/blog/article_snippet.jinja2' %}

pyrengine/templates/blog/article_snippet.jinja2
  
    <div id="c-inner-{{ comment.id }}">
      <a name="comment-{{ comment.id }}"></a>
      <div class="title">
        {% if comment.user is not none %}
          {{ h.user_link(comment.user) }}
        {% else %}
          {{ _('Guest:') }} <span class="name">{{ comment.display_name }}</span>
        {% endif %}
        | <span class="date">{{ h.timestamp_to_str(comment.published, _('DATE_TIME_SHORT')) }}</span>
        {% if admin_permission %}
        | {{ _('IP address:') }} <span class="name comment-ip-address">{{ comment.ip_address }}</span>
          {% if comment.xff_ip_address is not none %}
            ({{ _('X-Forwarded-For') }} <span class="name comment-ip-address">{{ comment.xff_ip_address }}</span>)
          {% endif %}
        | {{ _('Email:') }} <span class="name comment-email">{% if comment._real_email is none %}∅{% else %}{{ comment._real_email }}{% endif %}</span>
        {% endif %}
      </div>
      <div class="body">{{ comment.rendered_body | safe }}</div>
      <div class="links">
        <a href="#comment-{{ comment.id }}"><span class="fa fa-link"></span></a>
        <a href="#" onclick="pyrengine.replyToComment('{{ comment.id }}'); return false;">{{ _('reply to this comment') }}</a>
        {% if admin_permission %}
          {% if not comment.is_approved %}
          <a href="#" onclick="pyrengine.approveComment('{{ url_for('blog.approve_comment_ajax', comment_id=comment.id) }}', '{{ comment.id }}'); return false;" id="ca-{{ comment.id }}" class="border-icon">{{ _('approve') }}</a>  
          {% endif %}
          <a href="#" onclick="pyrengine.showCommentEditForm('{{ url_for('blog.edit_comment_ajax', comment_id=comment.id) }}', '{{ url_for('blog.comment_fetch_ajax', comment_id=comment.id) }}', '{{ comment.id }}'); return false;" title="{{ _('edit') }}"><span class="fa fa-edit"></span></a>
          <a href="#" onclick="pyrengine.deleteComment('{{ url_for('blog.delete_comment_ajax', comment_id=comment.id) }}', '{{ comment.id }}'); return false;" id="cd-{{ comment.id }}" title="{{ _('delete') }}"><span class="fa fa-trash-o"></span></a>
        {% endif %}
      </div>
    </div>

pyrengine/templates/blog/comments_moderation.jinja2
{% extends 'base.jinja2' %}

{% block title %}{{ _('Comments moderation') }}{% endblock %}

{% block content %}
<h2>{{ _('Comments moderation') }}</h2>

<div class="comments-moderation-queue">

{% for comment in comments %}
<div class="comment" id="c-{{ comment.id }}">
  <div class="title">
  {% if comment.user is not none %}
  <span class="name">{{ h.user_link(comment.user) | safe }}</span>
  {% else %}
  <span class="name">{{ comment.display_name }}</span>
  {% endif %}
  | <span class="name comment-email">{{ _('E-mail') }}: {% if comment._real_email is none %}∅{% else %}comment._real_email{% endif %} </span>
  | <span class="name">{{ _('Visitor website') }}: {% if comment.website %}comment.website{% else %}∅{% endif %}</span>
  | {{ _('IP address:') }} <span class="name comment-ip-address">{{ comment.ip_address }}</span>
    {% if comment.xff_ip_address is not none %}
      ({{ _('X-Forwarded-For') }} <span class="name comment-ip-address">{{ comment.xff_ip_address }}</span>)
    {% endif %}
  | <a href="{{ h.article_url(comment.article) }}#comment-{{ comment.id }}">{{ _('link') }}</a>
  </div>

  <div class="links">
    <a href="#" onclick="pyrengine.approveComment('{{ url_for('blog.approve_comment_ajax', comment_id=comment.id) }}', '{{ comment.id }}'); return false;" id="ca-{{ comment.id }}" class="border-icon">{{ _('approve') }}</a>
    <a href="#" onclick="pyrengine.deleteComment('{{ url_for('blog.delete_comment_ajax', comment_id=comment.id) }}', '{{ comment.id }}'); return false;" id="cd-{{ comment.id }}" class="border-icon">{{ _('delete') }}</a>
  </div>

  {% if comment._truncated_body is not none %}
    <div class="body" id="c-c-{{ comment.id }}"><p>{{ comment._truncated_body }} <a href="#" onclick="Pyrone_article_expandModeratedComment('{{ comment.id }}'); return false;">{{ _('expand...') }}</a></p></div>
    <div class="body" id="c-e-{{ comment.id }}" style="display: none;">{{ comment.rendered_body | safe }}</div>
  {% else %}
    <div class="body">{{ comment.rendered_body | safe }}</div>
  {% endif %}
</div>
{% endfor %}

</div>
{% endblock %}

pyrengine/templates/blog/edit_article.jinja2
{% extends 'base.jinja2' %}
{% import 'macros/forms.jinja2' as forms %}

{% block title %}{% if mode == 'create' %}{{ _('Write a new article') }}{% else %}{{ _('Edit article') }}{% endif %}{% endblock %}

{% block content %}
<form action="{{ submit_url }}" method="POST" id="form" onsubmit="return pyrengine.articleCheckForm();">
  <dl class="form">
    {{ forms.textfield('title', form['title'], _('Subject (required)'), '', errors['title']) }}
    {{ forms.textfield('shortcut', form['shortcut'], _('Shortcut (required)'), _('Short string (part of the URL), alphanumeric characters and “-” are recommended.'), errors['shortcut']) }}
    {{ forms.textfield('published', form['published'], _('Publishing date and time'), _('Format: YYYY-MM-DD HH:MM'), errors['published']) }}
    {{ forms.textfield('tags', form['tags'], _('Tags (comma separated)'), '', errors['tags']) }}

    <div>{{ _('Article body (required, markup: *<em>italic</em>*, **<strong>bold</strong>**, [hyperlink](http://example.com) <a href="{0}" target="_blank" class="new-window">more</a>)').format(url_for('blog.article_markup_help')) }}</div>

    <!-- body text control buttons -->
    <div class="editor-text-controls">
      <span class="button" onclick="pyrengine.editorWrap('fid-body', '`');" title="{{ _('Inline code (monospace text)') }}">`$x`</span>
      <span class="button" onclick="pyrengine.editorWrap('fid-body', '*');" title="{{ _('Emphasis (italic)') }}"><em>I</em>&nbsp;</span>
      <span class="button" onclick="pyrengine.editorWrap('fid-body', '**');" title="{{ _('Strong text (bold)') }}"><strong>B</strong></span>
      <span class="button" onclick="pyrengine.editorBlockquote('fid-body');" title="{{ _('Quotation') }}">&gt;</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '❈ ❈ ❈ {@class=center}\n');" title="{{ _('Insert dinkus') }}">❈ ❈ ❈</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '────────────────── {@class=center}\n');" title="{{ _('Insert dinkus') }}">──</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '══════════════════ {@class=center}\n');" title="{{ _('Insert dinkus') }}">══</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '~~~~~shell-session\n[user@shell]% \n~~~~~\n');" title="{{ _('Insert shell code') }}">sh $</span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '{@style=color:red;}');" title="{{ _('Insert paragraph color text') }}"><span style="color: red;">red</span></span>
      <span class="button" onclick="pyrengine.editorReplace('fid-body', '[TEXT](https://)');" title="{{ _('Insert hyperlink template') }}">&lt;a&gt;</span>
    </div>

    {{ forms.textarea('body', form['body'], '', '', errors['body']) }}
    {{ forms.checkbox('is_draft', form['is_draft'], none, _('draft article'), _('if checked article will not be available to everyone')) }}
    {{ forms.checkbox('is_commentable', form['is_commentable'], none, _('allow visitors comments'), '') }}

    <dd>{% if mode == 'edit' %}{{ forms.button(_('save and continue editing'), '', "pyrengine.saveArticle('" + url_for('blog.edit_article_ajax', article_id=article_id) + "'); return false;") }} {% endif %}
    {{ forms.button(_('save'), 'fa fa-save', "$('#form').submit(); return false;") }}
    {{ forms.button(_('preview'), 'fa fa-flask', "pyrengine.previewArticle(); return false;") }}
  </dl>
</form>

<div id="eid-article-notify" class="panel notify" style="display:none;"></div>
<div id="eid-article-warning" class="panel warning" style="display:none;"></div>
<div id="eid-article-render-preview" style="display: none;"></div>

{% endblock %}

pyrengine/templates/blog/index.jinja2
{% extends 'base.jinja2' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
{% for article in articles %}
<div class="article-preview">
  <div class="title">
    {% if editor_permission %}
      <div class="article-actions">
        <a href="{{ url_for('blog.edit_article', article_id=article.id) }}" class="border-icon" title="{{ _('edit') }}"><span class="fa fa-edit"></span></a>
        <a href="#" onclick="pyrengine.deleteArticle('{{ url_for('blog.delete_article_ajax', article_id=article.id) }}', '{{ article.id }}'); return false;" class="border-icon" title="{{ _('delete') }}" id="a-d-{{ article.id }}"><span class="fa fa-trash-o"></span></a>
      </div>
    {% endif %}
    <a href="{{ h.article_url(article) }}">{{ article.title }}</a>{% if article.is_draft %} <span class="panel warning">{{_('draft') }}</span>{% endif %}</a>
  </div>
  <div class="date">{{ '{author} | {date}'.format(author=article.user.display_name, date=h.timestamp_to_str(article.published, _('DATE_TIME_SHORT'))) }}</div>
  <div class="before-preview"></div>
  <div class="preview">{{ article.get_html_preview() | safe }}</div>
  {% if article.is_splitted %}<div class="splitter"><a href="{{ h.article_url(article) }}">{{ _('read more') }} <span class="fa fa-arrow-right"></span></a></div>{% endif %}
  <div class="tags">{% for tag in article.tags %}<a href="{{ url_for('blog.articles_by_tag', tag=tag.tag) }}">{{ tag.tag }}</a> {% endfor %}</div>
  <div class="footer">
    {% if article.comments_approved > 0 %}
      <a href="{{ h.article_url(article) }}#comments">{{ _('Comments:') }} {{ article.comments_approved }}</a>
    {% else %}
      {{ _('Comments:') }} 0
    {% endif %}
    {% if admin_permission %}
      / {{ _('not approved comments:') }} <span class="hint">{% if article.comments_total-article.comments_approved == 0 %}0{% else %}{{ article.comments_total-article.comments_approved }}{% endif %}</span>
    {%  endif %}
  </div>
</div>
<div class="article-preview-after"></div>
{% endfor %}

{% if articles|length == 0 %}
  {{ _('No articles here.') }}
{% endif %}

<div class="pager">
{% if next_page is none %} {{ _('<-newer') }} {% else %} <a href="{{ next_page }}">{{ _('<-newer') }}</a> {% endif %}
{% if prev_page is none %} {{ _('older->') }} {% else %} <a href="{{ prev_page }}">{{ _('older->') }}</a> {% endif %}
</div>

{% endblock %}

pyrengine/templates/blog/view_article.jinja2
{% extends 'base.jinja2' %}
{% import 'macros/forms.jinja2' as forms %}

{% set user_authenticated = current_user.is_authenticated %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
<script language="javascript">
$(document).ready(function() {
	// scroll to required position
	var hash = window.location.hash, 
		comment_id = -1;
		
	// extract comment id
	if (/#comment-([0-9]+)$/.test(hash)) {
		comment_id = RegExp.$1;
	} else {
		return;
	}
	
	var cb = $('#c-'+comment_id);
	if (cb) {
		cb.addClass('active');
	}
});
</script>

<div class="panel notify" style="display:none;" id="notify-block"></div>

<div class="article">
  <div class="title">
    {% if editor_permission %}
    <div class="article-actions">
     <a href="{{ url_for('blog.edit_article', article_id=article.id) }}" class="border-icon" title="{{ _('edit') }}"><span class="fa fa-edit"></span></a>
     <a href="#" onclick="pyrengine.deleteArticle('{{ url_for('blog.delete_article_ajax', article_id=article.id) }}', '{{ article.id }}'); return false;" class="border-icon" title="{{ _('delete') }}" id="a-d-{{ article.id }}"><span class="fa fa-trash-o"></span></a>
    </div>
    {% endif %}
    {{ article.title }} {% if article.is_draft %}<span class="panel warning">{{ _('draft') }}</span>{% endif %}
  </div>
  
  <div class="subtitle">
    <div class="date">{{ _('Published {0}').format(h.timestamp_to_str(article.published, _('DATE_TIME_SHORT'))) }}</div>
    <div class="clear-both"></div>
    {% if article.tags|length > 0 %}
    <div class="tags">{% for tag in article.tags %}<a href="{{ url_for('blog.articles_by_tag', tag=tag.tag) }}">{{ tag.tag }}</a> {% endfor %}</div>
    {% endif %}
  </div>
  <div class="body">{{ article.rendered_body | safe }}</div>
</div>


<h4><a name="comments"></a>{{ _('Comments') }}</h4>

<div class="article-comments">
  {% for comment in comments %}
  <div class="article-comment{% if not comment.is_approved %} not-approved{% endif %}" id="c-{{ comment.id }}" style="margin-left: {{ 50*comment._indent }}px">
  {% include '/blog/article_snippet.jinja2' %}
  </div>

  {% endfor %}

  {% if admin_permission %}
  <!-- edit comment form here -->
  <div class="article-inline-comment-edit" id="c-edit" style="display: none;">
  <form>
  <input type="hidden" id="c-edit-comment_id">
  <div> <input type="text" id="c-edit-name" class="display-name" title="{{ _('Display name of the visitor') }}"> 
    <input type="text" id="c-edit-date" title="{{ _('Comment date and time') }}" class="date">
    <label><input id="c-edit-is_subscribed" type="checkbox">{{ _('subscribed') }}</label>
  </div> 
  <div> <input type="text" id="c-edit-email" class="display-name" title="{{ _('Email address of the visitor') }}">
    <input type="text" id="c-edit-ip" title="{{ _('Visitor ip address') }}" class="ip">
    <input type="text" id="c-edit-xffip" title="{{ _('Visitor X-Forwarded-For address') }}" class="ip"> 
    <input type="text" id="c-edit-website" title="{{ _('Visitor website') }}" class="display-name"> 
  </div>
  
  <div><textarea id="c-edit-body" class="body"></textarea></div>
  <div><button class="button" onclick="pyrengine.submitArticleCommentEditForm('{{ url_for('blog.edit_comment_ajax', comment_id='666') }}'); return false;"><span class="fa fa-save"></span> {{ _('save') }}</button>
    <a href="#" onclick="pyrengine.cancelArticleCommentEditForm(); return false;">{{ _('close') }}</a>
  </div>
  
  </form>
  </div>
  {% endif %}

  
  {% if article.is_commentable %}
  <!-- new comment form here -->
  <div class="article-new-comment" id="c--1">
    <a name="leave-comment"></a>
    <a href="#" id="eid-leave-comment-link-bottom" style="display:none;" onclick="pyrengine.replyToArticleComment(-1); return false;">{{ _('leave comment') }}</a>
    <form action="{{ url_for('blog.add_article_comment', article_id=article.id) }}" method="POST" id="eid-comment-form">
      <input type="hidden" id="fid-parent-comment" value="">
      <input type="hidden" id="fid-article_id" value="{{ signature }}">
      <dl class="form">
        <dd><div id="eid-comment-error" style="display: none;" class="error"></div></dd>
        <dd><div id="eid-comment-notify" style="display: none;" class="panel notify"></div></dd>
        <dt>{{ _('Comment text (allowed markup: *<em>italic</em>*, **<strong>bold</strong>**, [hyperlink](http://example.com) or &lt;http://example.com>)')|safe }}
        {% if not user_authenticated %}
        {{_('<strong>Please pay attention that comments with more than one hyperlink (including field "website") will be put on moderation.</strong>') | safe }}
        {% endif %}
        </dt>
        <dd><textarea name="body" class="small" id="fid-comment-body"></textarea></dd>
        {% if user_authenticated %}
        {{ forms.checkbox('is_subscribed', is_subscribed, none, _('Subscribe to answers'), '') }}
        <!--<dd>${h.user_link(user)|n}</dd>-->
        <input type="hidden" id="fid-comment-displayname" value="">
        <input type="hidden" id="fid-comment-email" value="">
        <input type="hidden" id="fid-comment-website" value="">
        {% else %}
        {{ forms.textfield('comment-displayname', comment_display_name, _('Your name (required, 50 characters or less)')) }}
        {{ forms.textfield('comment-email', comment_email, _("Your email (optional, won't be published, required if you want to receive answers)")) }}
        {{ forms.checkbox('is_subscribed', is_subscribed, none, _('Subscribe to answers'), '') }}
        {{ forms.textfield('comment-website', comment_website, _('Your website')) }}
        {% endif %}
        <dd><button class="button" onclick="pyrengine.postArticleComment(); return false;"><span class="fa fa-comment-o"></span> {{ _('post comment') }}</button>
      </dl>
    </form>
  </div>
  {% else %}
  <div>{{ _('commenting is disabled') }}</div>
  {% endif %}

</div>
{% endblock %}